name: Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - name: Install Python 3.10.13
        uses: actions/setup-python@v4
        with:
            python-version: "3.10.13"

      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
    
      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install
        env:
          POETRY_VIRTUALENVS_IN_PROJECT: true

      - name: Install pre-commit
        run: |
          poetry run pre-commit install
  
      - name: Run pre-commit for Flake8, Black, isort
        run: |
          poetry run pre-commit run --all-files
