name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Install Python 3.11
        uses: actions/setup-python@v4
        with:
            python-version: "3.11"
      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Add Poetry to PATH
        run: |
          export PATH="$HOME/.local/bin:$PATH"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          poetry install

      - name: Run tests with coverage
        run: |
          poetry run pytest --cov-report=xml:/tmp/coverage.xml --cov=moral_keeper_ai --cov-branch --disable-warnings --cov-report=term-missing
